### ISSUE TITLE
log spammed with latest version

### ISSUE THREAD

**Issue by maevius669** [SilverAndro/Lootbeams#10]
beams aint showing and im getting this running lootbeams 2.1.1 

```
[Render thread/INFO]: [STDERR]: java.lang.NoSuchMethodError: 'java.util.List net.minecraft.class_1799.method_7950(net.minecraft.class_1657, net.minecraft.class_1836)'
[Render thread/INFO]: [STDERR]: 	at dev.silverandro.lootbeams.ColorGetter.getFromStack(ColorGetter.java:30)
[Render thread/INFO]: [STDERR]: 	at dev.silverandro.lootbeams.ColorGetter.getColor(ColorGetter.java:21)
[Render thread/INFO]: [STDERR]: 	at dev.silverandro.lootbeams.LootbeamsClient.lambda$onInitializeClient$1(LootbeamsClient.java:37)
[Render thread/INFO]: [STDERR]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[Render thread/INFO]: [STDERR]: 	at dev.silverandro.lootbeams.LootbeamsClient.lambda$onInitializeClient$3(LootbeamsClient.java:34)
[Render thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:63)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_638.handler$cel000$fabric-lifecycle-events-v1$tickWorldAfterBlockEntities(class_638.java:3108)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_638.method_18116(class_638.java:266)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1574(class_310.java:1956)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1246)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:882)
[Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:256)
[Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
[Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
[Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by SilverAndro** [comment]
can you provide the full log

**Comment by maevius669** [comment]
forgot to report that this happens with `printErrors=true`
minecraft 1.21.1

https://mclo.gs/1HuDCnP

![image](https://github.com/user-attachments/assets/892ac15f-91fe-4c27-90fb-9e9bf228178e)

**Comment by SilverAndro** [comment]
looks like the update i made broke the implicit 1.21 support, ill make a dedicated version for it in a bit

**Comment by SilverAndro** [comment]
`2.1.2+1.21.1` should work
