### ISSUE TITLE
Does nothing on 1.21......

### ISSUE THREAD

**Issue by RustyDagger** [SilverAndro/Lootbeams#9]
Iv changed config settings and messed around with it for 30 min nothing i do seems to make a beam show up.
Should mention it needs fabric API somewhere too.

**Comment by SilverAndro** [comment]
i never tested it on 1.21, ive fixed the version listing

**Comment by azhippy** [comment]
Error messages from log in 1.21 after changing config to not swallow errors. The error repeats continuously. 

[17:58:33] [Render thread/INFO]: [STDERR]: java.lang.NoSuchMethodError: 'java.util.List net.minecraft.class_1799.method_7950(net.minecraft.class_1657, net.minecraft.class_1836)'
[17:58:33] [Render thread/INFO]: [STDERR]: 	at dev.silverandro.lootbeams.ColorGetter.getFromStack(ColorGetter.java:30)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at dev.silverandro.lootbeams.ColorGetter.getColor(ColorGetter.java:21)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at dev.silverandro.lootbeams.LootbeamsClient.lambda$onInitializeClient$1(LootbeamsClient.java:37)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at dev.silverandro.lootbeams.LootbeamsClient.lambda$onInitializeClient$3(LootbeamsClient.java:34)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:63)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_638.handler$eje000$quilted_fabric_lifecycle_events_v1$tickWorldAfterBlockEntities(class_638.java:9108)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_638.method_18116(class_638.java:266)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1574(class_310.java:1956)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1246)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:882)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:256)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[17:58:33] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
